### ISSUE TITLE
StrawberryBushBlock and AdzukiSproutsBlock have inaccessible crop age field (Mod Compat)

### ISSUE THREAD

**Issue by HyDefier** [minecraftabnormals/Neapolitan#111]
Neapolitan currently uses an IntegerProperty for AGE that cannot be symbolically accessed by other mods. You can inherit CropBlock and make AGE accesible in getAgeProperty() so other mods can access your crops' age in their code.

**Comment by bageldotjpg** [comment]
Like Sweet Berry Bushes, neither of these are traditional crops, so I do not want them to be made Crop Blocks. I believe other mods can get the age property via checking the property list for a property named age, though.
