### ISSUE TITLE
Le crash

### ISSUE THREAD

**Issue by thelegitdolt** [minecraftabnormals/Neapolitan#117]
https://gist.github.com/thelegitdolt/935658a86b50febf7f1e8f995a98d21b

https://gist.github.com/thelegitdolt/07feb4af871d62544a305a83aaf3791d

**Comment by thelegitdolt** [comment]
happens when you hit a mob with a bananarrow

**Comment by thelegitdolt** [comment]
incompatability with  https://www.curseforge.com/minecraft/mc-mods/not-enough-gamerules

**Comment by bageldotjpg** [comment]
Issue on their end
