### ISSUE TITLE
1.18.2 - 3.0.0

### ISSUE THREAD

**Issue by kuddyh3ct0r** [minecraftabnormals/Neapolitan#118]
![2022-07-19_16 40 30](https://user-images.githubusercontent.com/109633944/179866369-a8bba9f0-a73e-4550-9a57-d905bd441607.png)
The chimps can't pick up bananas and just stare at them👁️👁️

**Comment by bageldotjpg** [comment]
Do you have mob griefing off?

**Comment by kuddyh3ct0r** [comment]
turning it on fixed it tysm :)

**Comment by kuddyh3ct0r** [comment]
![2022-07-20_14 41 49](https://user-images.githubusercontent.com/109633944/180087384-bb59261e-3838-4382-a70c-b09aaabfd015.png)
Also upside down corner Thatch Stairs are bugged.
