### ISSUE TITLE
upside down corner Thatch Stairs are bugged.

### ISSUE THREAD

**Issue by kuddyh3ct0r** [minecraftabnormals/Neapolitan#122]
![2022-07-29_18 13 03](https://user-images.githubusercontent.com/109633944/181864682-d73842ac-dc0c-4079-989a-5dc7ca01fd35.png)
upside down corner thatch stairs are bugged

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/neapolitan/commit/5861819523f543467a1c2824ded27ed15df652e3
