### ISSUE TITLE
Other mods start to crashing randomly

### ISSUE THREAD

**Issue by GatoLeyo** [minecraftabnormals/Neapolitan#126]
Whenever I put Neapolitan on the mods file other mods start crashing, it stops when I remove Neapolitan.
It started with Enchanting Infuser, I tried removing that mod but then Guns without Roses along with Domestication Innovation showed random errors, I removed them then Farmer's Delight crashed, then Cloud Storage and when all of them got removed it finally worked. 

Here's the Crash log with Cloud Storage
https://pastebin.com/6Y69gGyY

**Comment by GatoLeyo** [comment]
PD: the crash log has the previous last version of Neapolitan but I have the same errors with the latest versions as well

**Comment by bageldotjpg** [comment]
Neapolitan doesn't work on 1.19.2 yet.
