### ISSUE TITLE
Crash under 1.19.2

### ISSUE THREAD

**Issue by Zygus42** [minecraftabnormals/Neapolitan#127]
blueprint-1.19-6.0.7
neapolitan-1.19-4.0.1
forge-1.19.2-43.1.25-installer

[crash-2022-09-14_21.05.30-client.txt](https://github.com/team-abnormals/neapolitan/files/9566529/crash-2022-09-14_21.05.30-client.txt)

**Comment by bageldotjpg** [comment]
Fixed in 494700553c12fb85064d54bc1668302d17b32af3
