### ISSUE TITLE
Compat issue with Mekanism and Farmers' Delight

### ISSUE THREAD

**Issue by MasterIMLG** [minecraftabnormals/Neapolitan#129]
When using this mod along with Mekanism and Farmer's Delight, it crashes on start up. Launcher reports that caught an exception when MEK tried to register item, or even has no specific launcher report.

Game Version: 1.19.2
Forge Version: 43.1.25
Launcher: HMCL v3.5.3

Tested with Mods:
blueprint-1.19-6.0.7.jar
neapolitan-1.19-4.0.1.jar
FarmersDelight-1.19-1.1.2.jar
Mekanism-1.19.2-10.3.3.470.jar

Here's related crash reports:
[crash-2022-09-20_15.01.15-client.txt](https://github.com/team-abnormals/neapolitan/files/9604909/crash-2022-09-20_15.01.15-client.txt)
[crash-2022-09-20_14.45.20-client.txt](https://github.com/team-abnormals/neapolitan/files/9604910/crash-2022-09-20_14.45.20-client.txt)

**Comment by bageldotjpg** [comment]
Fixed in 494700553c12fb85064d54bc1668302d17b32af3
