### ISSUE TITLE
Minecraft Doesn't Open

### ISSUE THREAD

**Issue by Soul-Rack** [minecraftabnormals/Neapolitan#131]
Forge: 43.1.34
Minecraft: 1.19.2
When I have this mod in my mod files the game doesn't open, the launcher page works fine but when I try to start the game it won't open. I have tried this with and without the mod to see if it was another problem, but it's the mod doesn't let it start. Can you fix this?

**Comment by bageldotjpg** [comment]
Re-open with a crash report if possible
