### ISSUE TITLE
Vanilla vines expanding horizontally

### ISSUE THREAD

**Issue by MrFastZombie** [minecraftabnormals/Neapolitan#132]
Possibly an interaction with Nature's Aura? These vanilla vines extended horizontally for several chunks, and rapidly but it did eventually stop.

Mod version: 3.0
Forge: 40.1.69
Minecraft: 1.18.2
![2022-10-26_02 08 09](https://user-images.githubusercontent.com/18253497/197960013-f4bc374e-c61a-4013-920a-6ad901078c9a.png)
![2022-10-26_02 08 25](https://user-images.githubusercontent.com/18253497/197960029-fb503a74-e091-4b0d-9472-240abf9f2ebb.png)

**Comment by bageldotjpg** [comment]
Looks like nature's aura is probably bonemealing them in some form
