### ISSUE TITLE
Underground Growing

### ISSUE THREAD

**Issue by GangstaPichu** [minecraftabnormals/Neapolitan#138]
Is stuff in the mod able to grow on their own underground? I can bonemeal them, but they don't seem to want to grow on their own. 

![image](https://user-images.githubusercontent.com/88961592/204845462-1ff12653-f59d-467f-8116-000b67fb2463.png)

1.19.2
Ver: 4.0.2
Forge: 43.1.53
Modpack: Valhelsia 5

**Comment by bageldotjpg** [comment]
Strawberries need a higher light level of 13 to grow
