### ISSUE TITLE
I eat Slice of Strawberry Cake. Game Crashes.

### ISSUE THREAD

**Issue by shrooompy** [minecraftabnormals/Neapolitan#144]
Part of Modpack Better Minecraft Forge 1.18.2

 exit code:
-805306369

error msg:
The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "com.cursedcauldron.wildbackport.common.effects.EffectFactor.getFactorCalculationData()" because the return value of "com.cursedcauldron.wildbackport.common.effects.EffectFactor.of(net.minecraft.world.effect.MobEffect)" is null

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/abnormals-delight/commit/4aba618b2388f0fe239570f90c9bd822f4e06b27 I believe
