### ISSUE TITLE
When Quark is installed, all Ice Cream items have tooltips that show "rotten" food icons

### ISSUE THREAD

**Issue by juebster** [minecraftabnormals/Neapolitan#145]
Quark's hunger-related "Improved Tooltips" options wrongfully label all 7 flavors of ice cream as bad saturation items, likely because of the brief slowness debuff they give.

- "Food Tooltips" shows rotten hunger icons instead of normal, healthy ones
- "Show Saturation" labels the flavors as "Questionable Rations" (except for Neapolitan Ice Cream, which shows "Disturbingly Hearty", due to its higher restoration)

**Comment by bageldotjpg** [comment]
Quark issue, since Slowness is a negative effect it labels them all as 'poison'
