### ISSUE TITLE
Add tooltip to banana frond hinting at the need for rain

### ISSUE THREAD

**Issue by TheDeviantCrafter** [minecraftabnormals/Neapolitan#147]
Banana growth mechanics aren't very intuitive. I had to join the Discord server to find them.

I suggest adding a tooltip like "Looks dry - rain might help" to clue the player in.

**Comment by fivelol** [comment]
minecraft doesn't really do tooltips, even on very significant items (usually this kinda thing is indicated with an advancement), but the intuitiveness of banana growth is something we will definitely be addressing
