### ISSUE TITLE
Allow banana fronds to grow in jungle biomes without rain

### ISSUE THREAD

**Issue by TheDeviantCrafter** [minecraftabnormals/Neapolitan#148]
I play on a server with rain disabled via gamerule, so there's no way for me to farm banana stalks. Allowing fronds to grow in jungle biomes seems like a good way to accommodate players like myself without removing the rain restriction.

As a bonus it gives players a reason to make an outpost in a jungle biome.

**Comment by fivelol** [comment]
I don't think we should be designing the mod around niche circumstances, sorry. We're very happy with how the rain dependency initially creates a sort of seasonal harvest and it can be somewhat overcome by spreading chimp civilization to have them harvest for you. There are also vanilla features that you're being locked of like a use for lightning rods, powder snow, trident enchantments.
