### ISSUE TITLE
Server Crash with latest Github build 

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Neapolitan#15]
https://pastebin.com/F100sAZQ
Was testing if banana build was stable on a my server. Not sure if this is how we report server crashes lol so if I'm wrong please correct me.

**Comment by bageldotjpg** [comment]
Can you send the crash report from the crash reports folder? Also, was this in game or on start up?

**Comment by WitheredWasabi** [comment]
There's no crash-report that comes with it but I'll send latest.log:
[latest.log](https://github.com/minecraftabnormals/Neapolitan/files/5254592/latest.log)
Also the crash is upon starting the server, I try to start my server from the panel and it just stops itself after awhile.
