### ISSUE TITLE
[1.19.2] 'Cone' and 'Scream' paintings never show up in survival mode

### ISSUE THREAD

**Issue by jogurciQ** [minecraftabnormals/Neapolitan#156]
I was playing on a custom made modpack and noticed that both of the paintings added by Neapolitan never show up in survival.
So then I made a new instance with just Blueprint and Neapolitan (to make sure this isn't some kind of mod comaptibility issue) and the same bug occured. 
Please fix this ASAP! I really need a screaming monkey in my bedroom.

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/neapolitan/commit/56c76f5022987e8772ed831923be954f8048699c
