### ISSUE TITLE
Add crop produce to `#forge:crops`

### ISSUE THREAD

**Issue by saltyseadoggo** [minecraftabnormals/Neapolitan#157]
You should add this mod's crop produce items to #forge:crops. This tag contains non-crop items that are dropped by crops, and is notably used by Create: Crafts & Additions for one of its biofuel recipes.
The items I would like to see added to this tag, based on what exists in it by default, are

"neapolitan:strawberries",
"neapolitan:white_strawberries",
"neapolitan:adzuki_beans",
"neapolitan:mint_leaves"

**Comment by bageldotjpg** [comment]
Since the plants in this mod are not actually crops, like sweet berries, they were not included in this tag on purpose.
