### ISSUE TITLE
Cows above pointed dripstone crashes the game 

### ISSUE THREAD

**Issue by CraftyG** [minecraftabnormals/Neapolitan#160]
Having a cow being above a block with pointed dripstone underneath causes the game to crash. Here's the report regarding this issue
[crash-2023-05-13-19.43.06-client.txt](https://bytebin.lucko.me/cVeHejFYL2)

**Comment by HanatakeYurii** [comment]
Cannot open your file...

**Comment by CraftyG** [comment]
> Cannot open your file...

Here's a more permanent link to the [report](https://pastebin.com/HgrE4SGu)

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/team-abnormals/neapolitan/commit/e1acab81a54ba408a54b91b3e23399bf5f0d19ed
