### ISSUE TITLE
[Compatibility Feature] Banana Stalk not tagged as Log

### ISSUE THREAD

**Issue by AdalynBlack** [minecraftabnormals/Neapolitan#161]
The Banana Stalk isn't tagged as being a log in the game, which prevents some mods from having expected interactions (i.e. the saw from Create can't break through it)
Adding the log tag would make it act more as expected in many situations

**Comment by bageldotjpg** [comment]
Banana Stalk is intentionally not tagged as a log, as it isn't one. It can't be made into planks and it is not wooden. Tagging it as a log would cause unintended and unforeseen issues.

**Comment by AdalynBlack** [comment]
Not being tagged as log also breaks compatibility with other mods like the create mod. Because it's not considered a log, create's saws can't cut down banana trees

**Comment by Kurizek27** [comment]
mushroom stem can be removed via saw so use one of these instead 

<img width="553" height="229" alt="Image" src="https://github.com/user-attachments/assets/8ab950d3-795d-43e0-8e09-5e9f8d887ffc" />
