### ISSUE TITLE
[1.19.2] Chimpanze worldgen placement crashes when min and max spawn attempts are both 0

### ISSUE THREAD

**Issue by sigmastar00** [minecraftabnormals/Neapolitan#163]
Installed mods:
Forge 43.2.17
Blueprint 6.1.2
Neapolitan 4.0.2

Using the following config causes a worldgen crash when trying to place chimpanzees:
```
[mobs.chimpanzee]
	#The percentage chance for a Banana Plant to generate with a group of Chimpanzees
	"Chimpanzee group chance" = 0.25
	#The maximum amount of Chimpanzees that can spawn with a Banana Plant
	"Chimpanzee maximum group size" = 0
	#The minimum attempts for Chimpanzees to spawn with a Banana Plant
	"Chimpanzee minimum spawn attempts" = 0
	#The maximum attempts for Chimpanzees to spawn with a Banana Plant
	"Chimpanzee maximum spawn attempts" = 0
```

I don't have a crash log because the game hangs when this happens, but i do have the game's output log which shows the exception: https://hastebin.com/share/eyupomipec.php

**Comment by HanatakeYurii** [comment]
Output log no longer available...

**Comment by sigmastar00** [comment]
Ah, sorry about that. Here's a new one: https://pastebin.com/MMtvtjeT

**Comment by DarkeFae** [comment]
I can confirm the server i help run is getting the same crash with an identical log:
[Log](https://github.com/DarkeFae/crash-reports/blob/main/Neopolitan/chimpanzee%20logs.log)

and also can confirm that it is solved by raising max spawn attempts to at least 1
