### ISSUE TITLE
Unable to find Mint

### ISSUE THREAD

**Issue by Erxti** [minecraftabnormals/Neapolitan#167]
Can I have more information to where mint can spawn, I searched and got multiple answer, some says it spawn in taiga, others says it's spawns in mountain near small lake sometimes under a tree, but even with thoses informations I still wasn't able to find it in mountains biome and taiga (i searched snowy taiga and others too) May I get some help please? (I'm playing Better Minecraft 3 on forge 1.19.2).

**Comment by bageldotjpg** [comment]
Mint generates semi rarely in any Windswept biome (#minecraft:is_hill)
