### ISSUE TITLE
Is it okay for this mod to use the textures of Neapolitan?

### ISSUE THREAD

**Issue by 1mtwtfss1** [minecraftabnormals/Neapolitan#169]
There is a new food mod called Mengfood, which uses the textures of Neapolitan. 
**Is it able to use the textures without your permission?**
What's more, it also use the textures of other mods such as Farmer's Delight, Seasonals and Exquisito.
I think it is not correct for this mod to use them. What do you think of it?

link: https://www.curseforge.com/minecraft/mc-mods/mengfood

This is its textures:
![QQ截图20231006141551](https://github.com/team-abnormals/neapolitan/assets/88222275/47226a86-8b2a-45d3-8849-98159fd8c07c)

**Comment by 1mtwtfss1** [comment]
The author of the mod says the textures are not completely the same as these mods, but he just modified some places of them.

**Comment by bageldotjpg** [comment]
That is not allowed, I will report the project and you are welcome to as well. Thanks for letting us know!
