### ISSUE TITLE
In Control! compatibility

### ISSUE THREAD

**Issue by SerJoG** [minecraftabnormals/Neapolitan#181]
Hi, I noticed that this mod is incompatible with In Control! mod that manages mob. In my case I'm a bit arachnophobic and I use that mod to prevent spider spawning but it doesn't work with neapolitan plantain spider, I'm sure that i use the right syntax.

Versions:
Minecraft 1.19.2
Neapolitan 1.19.2-4.1.0
InControl 1.19-7.1.12

**Comment by bageldotjpg** [comment]
Plantain spider spawning is fairly configurable, but InControl should work, it's pretty powerful and captures everything so I believe your syntax may be wrong. You could also try bad mobs.
