### ISSUE TITLE
Will this mod be updated for 1.20.1?

### ISSUE THREAD

**Issue by miraclematters** [minecraftabnormals/Neapolitan#182]
I loved this mod so so so so much, i feel weird not having it but i don't really want to downgrade. I just want to know if 1.20.1 support is planned for the future.

**Comment by neverdestroyer23** [comment]
idk too
hopefully it will though id love to play with farmer's delight 1.20.1 and this

**Comment by bageldotjpg** [comment]
Potentially eventually, maybe not specifically 1.20.1 but a form of 1.20 version is likely. Modded 1.20 is in a weird place due to mojang's changes.
