### ISSUE TITLE
Mint Milkshake crafting recipe consumes the bowl from the ice cream bowl used.

### ISSUE THREAD

**Issue by OrithanFox** [minecraftabnormals/Neapolitan#185]
Crafting Mint Milkshakes also consumes the bowl that is used for the ice cream. Other milkshake recipes don't have this issue.

**Comment by OrithanFox** [comment]
This is also an issue with the Adzuki Milkshake recipe too

**Comment by LaGz4643** [comment]
This also affects using Banana Ice Cream in crafting recipes. It seems that some items in [NeapolitanItems.java](https://github.com/team-abnormals/neapolitan/blob/1.19.x/src/main/java/com/teamabnormals/neapolitan/core/registry/NeapolitanItems.java) do not have a "craft remainder" item defined, namely Banana, Mint, and Adzuki Ice Cream and Milkshakes.
