### ISSUE TITLE
[1.20] sus banana plants sometimes lack exposed sus gravel

### ISSUE THREAD

**Issue by fivelol** [minecraftabnormals/Neapolitan#196]
I don't think this is a bug per se but if 1-2 bits are exposed there ideally won't be a gameplay loop of digging up every banana plant known to man because the gravel looks slightly wider

**Comment by bageldotjpg** [comment]
I don't really wanna guarantee one on top, it'll make the code a bit wonky, plus also if the gravel exceeds 3 blocks then its for sure suspicous (and there's also almost always a carved stalk)
