### ISSUE TITLE
Vanilla vines can grow more than 2 stages when bonemealed even when there's no block behind them

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Neapolitan#4]
![image](https://user-images.githubusercontent.com/38932715/90749924-f1e57d80-e288-11ea-9ee5-365b8708dd67.png)

**Comment by bageldotjpg** [comment]
Intended, you can bonemeal nether vines past their max limit.
You can also place vanilla past its max limit, just like cacti and sugar cane.
